### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by jarelllama** [FakesiteListHUN/FakeWebshopListHUN#2]
fruugo.hu

Official Hungary site of Fruugo. You can go to https://www.fruugo.us/ and scroll down to click on the Hungary site and see that the domain is the same.

**Comment by FakesiteListHUN** [comment]
Yes it's the official site, but the whole Fruugo company is a scam. On [scamadviser ](https://www.scamadviser.com/check-website/fruugo.com)it's has only 1 star reviews (.hu and .com either).
On [trustpilot](https://www.trustpilot.com/review/fruugo.hu) the .hu site has 1.2 stars (204 reviews), on Google the company has 1.6 stars (1400+ reviews), and also our group has people who are scammed by this company.

**Comment by jarelllama** [comment]
Thanks for the update. I'll look into Fruugo.
