### ISSUE TITLE
180.dk and viaota.com

### ISSUE THREAD

**Issue by jarelllama** [FakesiteListHUN/FakeWebshopListHUN#3]
Can you verify 180.dk and viaota.com are scams? I am unable to find bad reviews for viaota.com and 180 seems to be a legit company on the Google Play and App Store, along with decent reviews on Trustpilot.

**Comment by FakesiteListHUN** [comment]
Thank you for  let me know this. You are right 180.dk is not scam site, they just mentioned this scams sites (another auto scrapped bug), I fixed this. Viaota is a part of the UAB (EKOMLITA) company (whois check confirm this, also same phone number as on their other pages), a known scam company.
[viaota scamadviser](https://www.scamadviser.com/check-website/my.viaota.com), [ekomlita trustpilot](https://www.trustpilot.com/review/ekomlita.com) read the comments.

**Comment by jarelllama** [comment]
Thanks for checking
