### ISSUE TITLE
Please verify skg.com

### ISSUE THREAD

**Issue by jarelllama** [FakesiteListHUN/FakeWebshopListHUN#4]
Please verify if skg.com is a scam. Thank you.

**Comment by jarelllama** [comment]
I will whitelist the domain in the mean time. From all I see on Trustpilot/Amazon review, it seems legitimate.

**Comment by FakesiteListHUN** [comment]
The site has the questionable "ip@whosebilling.com" address [here](skg.com/pages/intellectual-property-rights) just like a lot of known scam site.

**Comment by jarelllama** [comment]
Hi. I just checked again and skg.com seems legitimate. They are even sold in my country at popular electronic stores.

**Comment by FakesiteListHUN** [comment]
Okay, I will whitelist the domain.
